### PR TITLE
CVE, license scanning and static code analysis

### PR DESCRIPTION
**Pull request by maoo**
This PR covers the security scanning needed to accept the contribution at FINOS - https://github.com/finos/community/issues/195

It includes:
- updated versions in requirements.txt - needs testing
- CVE scanning of direct and transitive dependencies - [passed](https://github.com/maoo/horizon-scanning-core/actions/runs/3319024749)
- Static code analysis - [4 issues found](https://github.com/maoo/horizon-scanning-core/actions/runs/3319024740/jobs/5483659997). Note that you may want to ignore some findings, read more on https://github.com/finos/security-scanning#static-code-analysis
- License scanning - [no unfriendly licenses found](https://github.com/maoo/horizon-scanning-core/actions/runs/3319546729/jobs/5484833081)

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @syn-sunilkumar,

Do you have an update on the acceptance of this PR as it would be great to merge prior to the FINOS TSC meeting?

Many thanks,

James.

**Comment by maoo** [comment]
One additional note that I forgot to mention in the PR body: the use of [Renovate](https://renovatebot.com/) (recommended) or Dependabot helps a lot in keeping the number of CVEs low. During the contribution process to FINOS, we will enable one of these 2 options.

**Comment by synechron-finlabs** [comment]
Hi James – Thanks fir this. We will take care of this by tomorrow.

 



Best Regards,  
Punit Shah



Specialist, FinLabs / Accelerators
 

From:
James McLeod ***@***.***>
Date: Monday, 7 November 2022 at 18:29
To: synechron-finlabs/horizon-scanning-core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL]: Re: [synechron-finlabs/horizon-scanning-core] CVE, license scanning and static code analysis (PR #1)








CAUTION: This email originated from outside the organization. Do not click links or open attachments
 unless you recognize the sender and know the content is safe. 






 






Hi 
@syn-sunilkumar,
Do you have an update on the acceptance of this PR as it would be great to merge prior to the FINOS TSC meeting?
Many thanks,
James.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you are subscribed to this thread.Message
 ID: ***@***.***>


Disclaimer:- This email, attachments and any information contained therein is intended solely for the use of the individual or entity to whom it is addressed and may be confidential and/or privileged data of Synechron. If you are not the intended recipient
 of this email, you are requested not to disclose the same and immediately notify the sender by reply email and further delete the said email along with any and all attachments appended thereto. Internet communications cannot be guaranteed to be timely, secure,
 error or virus-free. Synechron or any of its affiliates does not accept any liability for virus infected email or errors or omissions or consequences which may arise as a result of this email transmission.

**Comment by maoo** [comment]
Hi @syn-sunilkumar,
thanks for merging this PR!

Please note that the scanning is failing, see https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176 and https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177 .

It would be great if you could solve the issues mentioned in the action logs. Thank you!

**Comment by synechron-finlabs** [comment]
Thanks Maurizio, for your email.

We seek your assistance in fixing below issues.

 

https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176
Can you please help us locate/suggest the accepted version of XML.

https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177
We’ve used this module, as that is the core requirement of the application and, we’ve carefully implemented exception
 management to prevent any unwanted behavior by the users. So, in this case, how should we proceed ahead to close it.


 
Your assistance is highly appreciated.

 
Thank you.

 



Best Regards,  
Punit Shah
Specialist, FinLabs / Accelerators



 

From:
Maurizio Pillitu ***@***.***>
Date: Tuesday, 8 November 2022 at 11:20
To: synechron-finlabs/horizon-scanning-core ***@***.***>
Cc: BlockchainTechTeam ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL]: Re: [synechron-finlabs/horizon-scanning-core] CVE, license scanning and static code analysis (PR #1)








CAUTION: This email originated from outside the organization. Do not click links or open attachments
 unless you recognize the sender and know the content is safe. 






 






Hi 
@syn-sunilkumar,
thanks for merging this PR!
Please note that the scanning is failing, see 
https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176 and

https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177 .
It would be great if you could solve the issues mentioned in the action logs. Thank you!
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you modified the open/close state.Message
 ID: ***@***.***>


Disclaimer:- This email, attachments and any information contained therein is intended solely for the use of the individual or entity to whom it is addressed and may be confidential and/or privileged data of Synechron. If you are not the intended recipient
 of this email, you are requested not to disclose the same and immediately notify the sender by reply email and further delete the said email along with any and all attachments appended thereto. Internet communications cannot be guaranteed to be timely, secure,
 error or virus-free. Synechron or any of its affiliates does not accept any liability for virus infected email or errors or omissions or consequences which may arise as a result of this email transmission.

**Comment by maoo** [comment]
> https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176
> Can you please help us locate/suggest the accepted version of XML.

Not sure I understand the question about XML, maybe you meant `lxml`? CVE scanning is reporting issues with `lxml` version 4.5.0 ; on https://pypi.org/project/lxml/ the latest version is 4.9.1 , so I'd suggest to update your [requirements.txt](https://github.com/synechron-finlabs/horizon-scanning-core/blob/main/requirements.txt#L5) to point to its latest version.

More in general, I'd suggest to [enable Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) and follow its suggested updates.

> https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177
> We’ve used this module, as that is the core requirement of the application and, we’ve carefully implemented exception
 management to prevent any unwanted behavior by the users. So, in this case, how should we proceed ahead to close it.

The warning is due to the fact that Semgrep believes that you're importing a module with a dynamic name, due to the code `importlib.import_module(module_name)`  on https://github.com/synechron-finlabs/horizon-scanning-core/blob/main/agencies/esma/esma.py#L29 ; however, since you define `module_name` statically right above, this warning can be ignored; to fix it, you have 2 ways:

1. Use one line, like `module = importlib.import_module("agencies.{}.{}".format("esma",url))`
2. Add `#nosemgrep` in the line above `importlib.import_module(module_name)`

Try to make these changes and push into a branch, so that Github Actions can scan again; alternatively, [install semgrep locally](https://semgrep.dev/docs/getting-started/) and then run `semgrep scan --error --config auto` on your codebase.

**Comment by synechron-finlabs** [comment]
Hi – We’ve fixed the issues. Can you please check & confirm.

 
Thank you.

 



Best Regards,  
Punit Shah
Specialist, FinLabs / Accelerators



 

From:
Maurizio Pillitu ***@***.***>
Date: Tuesday, 8 November 2022 at 12:01
To: synechron-finlabs/horizon-scanning-core ***@***.***>
Cc: BlockchainTechTeam ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL]: Re: [synechron-finlabs/horizon-scanning-core] CVE, license scanning and static code analysis (PR #1)








CAUTION: This email originated from outside the organization. Do not click links or open attachments
 unless you recognize the sender and know the content is safe. 






 







https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176
Can you please help us locate/suggest the accepted version of XML.

Not sure I understand the question about XML, maybe you meant lxml? CVE scanning is reporting issues with
lxml version 4.5.0 ; on 
https://pypi.org/project/lxml/ the latest version is 4.9.1 , so I'd suggest to update your

requirements.txt to point to its latest version.
More in general, I'd suggest to 
enable Dependabot and follow its suggested updates.

https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177
We’ve used this module, as that is the core requirement of the application and, we’ve carefully implemented exception
management to prevent any unwanted behavior by the users. So, in this case, how should we proceed ahead to close it.

The warning is due to the fact that Semgrep believes that you're importing a module with a dynamic name, due to the code
importlib.import_module(module_name) on

https://github.com/synechron-finlabs/horizon-scanning-core/blob/main/agencies/esma/esma.py#L29 ; however, since you define
module_name statically right above, this warning can be ignored; to fix it, you have 2 ways:


Use one line, like module = importlib.import_module("agencies.{}.{}".format("esma",url))
Add #nosemgrep in the line above
importlib.import_module(module_name)
Try to make these changes and push into a branch, so that Github Actions can scan again; alternatively,

install semgrep locally and then run semgrep scan --error --config auto on your codebase.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you modified the open/close state.Message
 ID: ***@***.***>


Disclaimer:- This email, attachments and any information contained therein is intended solely for the use of the individual or entity to whom it is addressed and may be confidential and/or privileged data of Synechron. If you are not the intended recipient
 of this email, you are requested not to disclose the same and immediately notify the sender by reply email and further delete the said email along with any and all attachments appended thereto. Internet communications cannot be guaranteed to be timely, secure,
 error or virus-free. Synechron or any of its affiliates does not accept any liability for virus infected email or errors or omissions or consequences which may arise as a result of this email transmission.

**Comment by maoo** [comment]
yes, perfect. Thanks!

**Comment by synechron-finlabs** [comment]
It seems the test is still picking up old requirement.txt and not the new one. That’s why its failing.

 



Best Regards,  
Punit Shah



Specialist, FinLabs / Accelerators
 

From:
Punit Shah1 ***@***.***>
Date: Tuesday, 8 November 2022 at 16:54
To: synechron-finlabs/horizon-scanning-core ***@***.***>, synechron-finlabs/horizon-scanning-core ***@***.***>
Cc: BlockchainTechTeam ***@***.***>, State change ***@***.***>
Subject: Re: [EXTERNAL]: Re: [synechron-finlabs/horizon-scanning-core] CVE, license scanning and static code analysis (PR #1)

Hi – We’ve fixed the issues. Can you please check & confirm.

 
Thank you.

 



Best Regards,  
Punit Shah
Specialist, FinLabs / Accelerators



 

From:
Maurizio Pillitu ***@***.***>
Date: Tuesday, 8 November 2022 at 12:01
To: synechron-finlabs/horizon-scanning-core ***@***.***>
Cc: BlockchainTechTeam ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL]: Re: [synechron-finlabs/horizon-scanning-core] CVE, license scanning and static code analysis (PR #1)








CAUTION: This email originated from outside the organization. Do not click links or open attachments
 unless you recognize the sender and know the content is safe. 






 







https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701176
Can you please help us locate/suggest the accepted version of XML.

Not sure I understand the question about XML, maybe you meant lxml? CVE scanning is reporting issues with
lxml version 4.5.0 ; on 
https://pypi.org/project/lxml/ the latest version is 4.9.1 , so I'd suggest to update your

requirements.txt to point to its latest version.
More in general, I'd suggest to 
enable Dependabot and follow its suggested updates.

https://github.com/synechron-finlabs/horizon-scanning-core/actions/runs/3417701177
We’ve used this module, as that is the core requirement of the application and, we’ve carefully implemented exception
management to prevent any unwanted behavior by the users. So, in this case, how should we proceed ahead to close it.

The warning is due to the fact that Semgrep believes that you're importing a module with a dynamic name, due to the code
importlib.import_module(module_name) on

https://github.com/synechron-finlabs/horizon-scanning-core/blob/main/agencies/esma/esma.py#L29 ; however, since you define
module_name statically right above, this warning can be ignored; to fix it, you have 2 ways:


Use one line, like module = importlib.import_module("agencies.{}.{}".format("esma",url))
Add #nosemgrep in the line above
importlib.import_module(module_name)
Try to make these changes and push into a branch, so that Github Actions can scan again; alternatively,

install semgrep locally and then run semgrep scan --error --config auto on your codebase.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you modified the open/close state.Message
 ID: ***@***.***>


Disclaimer:- This email, attachments and any information contained therein is intended solely for the use of the individual or entity to whom it is addressed and may be confidential and/or privileged data of Synechron. If you are not the intended recipient
 of this email, you are requested not to disclose the same and immediately notify the sender by reply email and further delete the said email along with any and all attachments appended thereto. Internet communications cannot be guaranteed to be timely, secure,
 error or virus-free. Synechron or any of its affiliates does not accept any liability for virus infected email or errors or omissions or consequences which may arise as a result of this email transmission.

**Pull request merged**
